### ISSUE TITLE
error:FLANN：FLANN-NOTFOUND

### ISSUE THREAD

**Issue by 995122460Aa** [Practice3DVision/SLMaster#10]
在生成项目时，出现：
D:\user\SL\SLMaster-master\out\build\x64-Debug\ninja : error : 'FLANN::FLANN-NOTFOUND', needed by 'gui/CMakeFiles/SLMasterGui_autogen_timestamp_deps', missing and no known rule to make it

**Comment by Practice3DVision** [comment]
这是由于PCL的链接库重复导入而出现的问题。

已在主分支修复，请重新克隆主分支尝试编译。

如果这对您有帮助，请给个**Star**⭐喔。
