### ISSUE TITLE
[Compilation issue] algorithm 模块编译报错

### ISSUE THREAD

**Issue by azh-1415926** [Practice3DVision/SLMaster#16]
**Desktop (please complete the following information):**
 - Windows OS Version: [e.g. windows 11]
 - SLMaster Version: [e.g. master]
 - OpenCV Version: [e.g. 4.6.0]
 - VTK Version: [e.g. 9.2.0]
 - PCL Version: [e.g. 1.13.1]
 - Qt Version: [e.g. 5.15.2]

**Describe the compilation issue**
A clear and concise description of what the compilation issue is.

**Screenshots**
![image](https://github.com/Practice3DVision/SLMaster/assets/106266711/aeb43b7c-9dcd-4da4-9819-717b67fef82c)

**Additional context**
algorithm 模块编译报错

1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(277,16): error C2530: “slmaster::algorithm::leftUnwrapMap”: 必须初始化引用
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(277,56): error C2530: “slmaster::algorithm::InputArray”: 必须初始化引用
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(277,42): error C2146: 语法错误: 缺少“;”(在标识符“rightUnwrapMap”的前面)
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(277,56): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(278,29): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(278,17): error C2146: 语法错误: 缺少“;”(在标识符“disparityMap”的前面)
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(278,29): error C2059: 语法错误:“)”
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(278,37): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(278,37): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(290,5): error C2061: 语法错误: 标识符“OutputArray”
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(288,39): error C2511: “bool slmaster::algorithm::SinusCompleGrayCodePattern_Impl::decode(const std::vector<std::vector<cv::Mat,std::allocator<cv::Mat>>,std::allocator<std::vector<cv::Mat,std::allocator<cv::Mat>>>> &) const”:“slmaster::algorithm::SinusCompleGrayCodePattern_Impl”中没有找到重载的成员函数
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(9,7): message : 参见“slmaster::algorithm::SinusCompleGrayCodePattern_Impl”的声明
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(294,42): error C2065: “disparityMap”: 未声明的标识符
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(294,20): error C2530: “disparity”: 必须初始化引用
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(296,9): error C2065: “flags”: 未声明的标识符
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(316,9): error C2671: “slmaster::algorithm::SinusCompleGrayCodePattern_Impl::decode”: 静态成员函数没有“this”指针
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(316,9): error C2440: “<function-style-cast>”: 无法从“initializer list”转换为“slmaster::algorithm::SinusCompleGrayCodePattern_Impl::decode::<lambda_dc306bdc76441c55f11681eec3e73537>”
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(316,9): message : “slmaster::algorithm::SinusCompleGrayCodePattern_Impl::decode::<lambda_dc306bdc76441c55f11681eec3e73537>::<lambda_dc306bdc76441c55f11681eec3e73537>”: 函数不接受 5 个参数
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(316,9): message : 尝试匹配参数列表“(const std::vector<std::vector<cv::Mat,std::allocator<cv::Mat>>,std::allocator<std::vector<cv::Mat,std::allocator<cv::Mat>>>>, std::vector<cv::Mat,std::allocator<cv::Mat>>, std::vector<cv::Mat,std::allocator<cv::Mat>>, std::vector<cv::Mat,std::allocator<cv::Mat>>, std::vector<cv::Mat,std::allocator<cv::Mat>>)”时
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(302,9): error C2661: “cv::parallel_for_”: 没有重载函数接受 1 个参数
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(302,9): message : 尝试匹配参数列表“(cv::Range)”时
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusCompleGraycodePattern.cpp(319,9): error C2352: “slmaster::algorithm::SinusCompleGrayCodePattern_Impl::computeDisparity”: 调用非静态成员函数需要一个对象

1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusShiftGraycodePattern.cpp(151,22): error C2065: “range”: 未声明的标识符
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusShiftGraycodePattern.cpp(151,39): error C2065: “range”: 未声明的标识符
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusShiftGraycodePattern.cpp(168,6): error C2059: 语法错误:“)”
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusShiftGraycodePattern.cpp(171,5): error C2059: 语法错误:“if”
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusShiftGraycodePattern.cpp(171,29): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusShiftGraycodePattern.cpp(171,29): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>C:\Users\azh\Desktop\SLMaster-master\src\algorithm\cpuStructuredLight\sinusShiftGraycodePattern.cpp(216,24): error C2440: “<function-style-cast>”: 无法从“int”转换为“cv::Range”

**Comment by Practice3DVision** [comment]
请查看问题 #2 ，尝试更换CRLF与LF的更换。

**Comment by azh-1415926** [comment]
谢谢大佬，Thanks♪(･ω･)ﾉ
