### ISSUE TITLE
Compile OpenCV_Contrib Error	

### ISSUE THREAD

**Issue by zxdragon21** [Practice3DVision/SLMaster#2]
Dear Sir,
  When I was compiling OpenCV4.8.0 with opencv_contrib-liuyunhuang, vs2022 reported an error:	reference variable "cv::cuda::device::cudastructuredlight::params" requires an initializer	opencv_world	E:\opencv-4.8.0\modules\opencv_contrib-liuyunhuang\modules\cudastructuredlight\src\cuda\stereo_match.cu	201.
  The declaration of the function is:
void stereoMatch(const GpuMat &left, const GpuMat &right,
                 const StereoMatchParams &params, GpuMat &dispMap,
                 Stream &stream = Stream::Null()) 
  I don't think variable StereoMatchParams &params has any problem? Can you pls help to find out the issue?

Alex

**Comment by Practice3DVision** [comment]
In fact, this is caused by LF and CRLF. You can switch between LF and CRLF and try again.
Thank you very much for your feedback.

**Comment by Practice3DVision** [comment]
By the way, when your NVCC compiler is unable to find the Eigen header file, please manually add the Eigen included directory to the project in the Project Manager in VS. 
This is a bug in the NVCC compiler on Windows.

**Comment by zxdragon21** [comment]
Thank your for your reply.
I resolved the LF/CRLF issue.
However, CMake reports cannot find gflags. I tried compile gflags and glog from source and specified the directory, but it doesn't work. I use vs2022 as compilier.
Do you have any idea?

Alex

CMake Error at D:/opencv-4.8.0/build/CMakeFiles/CMakeTmp/cmTC_3c636Targets.cmake:37 (set_target_properties):
  The link interface of target "glog::glog" contains:
    gflags::gflags
but the target was not found.  Possible reasons include:
    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

**Comment by Practice3DVision** [comment]
I'm very sorry, I don't seem to have encountered this situation before. It seems like an issue with OpenCV.

Perhaps you can try compiling with the Opencv 4. x branch, as this is the branch I am currently using, but I am not sure if it will succeed.

Wishing you success.
