### ISSUE TITLE
[Runtime issue]

### ISSUE THREAD

**Issue by azh-1415926** [Practice3DVision/SLMaster#20]
作者大大，请问缺的这个动态库可以从哪里下
![image](https://github.com/Practice3DVision/SLMaster/assets/106266711/0a686352-4cb1-45d3-aecc-f1dfa4fd52b0)

**Comment by Practice3DVision** [comment]
见**README**编译部分第一条：

![image](https://github.com/Practice3DVision/SLMaster/assets/84160076/3c8134b9-6617-4b73-8116-fe7a622d37fe)

**Comment by azh-1415926** [comment]
好的，谢谢作者
