### ISSUE TITLE
SLMasterGui.exe在测试binocularCamera时遇到问题

### ISSUE THREAD

**Issue by BUPTAIScott** [Practice3DVision/SLMaster#30]
在使用release页面下载的exe程序测试data中的binocularCamera数据集时经常闪退或者卡住不动，操作流程是按照readme中的流程来的：离线模式——选择左、右文件夹——开始扫描——正弦互补格雷码——单次扫描，但没成功过。单目的数据集能正常运行，有纹理和点云。

**Comment by unlikehuman** [comment]
你好，请问这个问题解决了嘛，我遇到了同样的问题，想问问解决方法
